export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGIN_WITH_TOKEN = 'LOGIN_WITH_TOKEN';
export const START_HTTP_INTERCEPTORS = 'START_HTTP_INTERCEPTORS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
